### ISSUE TITLE
Add github actions release workflow

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-common#5]
- setting up standard release workflows
- will be taking a lot from adapters & core
- release as python package with standard CI checks
- if we use hatch, may need to redo some of the workflows (refactoring a step in the pipeline)

Blocked on https://github.com/dbt-labs/dbt-common/issues/10 & #6

**Comment by MichelleArk** [comment]
Will roll into https://github.com/dbt-labs/dbt-common/issues/5
