### ISSUE TITLE
[Maintainership] Add GitHub labels for `triage` and `awaiting_response` 

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-common#73]
### Housekeeping

- [X] I am a maintainer of dbt-common

### Short description

Add GitHub labels for `triage` and `awaiting_response` 

### Acceptance criteria

Labels exist here: https://github.com/dbt-labs/dbt-common/labels

### Suggested Tests

N/A

### Impact to Other Teams

None.

### Will backports be required?

No

**Comment by mikealfare** [comment]
Hopefully that wasn't too obnoxious.

**Comment by dbeatty10** [comment]
> Hopefully that wasn't too obnoxious.

No better proof that the labels are there!
