### ISSUE TITLE
update dbt-core to ref specific release of dbt-common

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-common#8]
- after porting over https://github.com/dbt-labs/dbt-common/issues/10
- after releasing 0.1.1 https://github.com/dbt-labs/dbt-common/issues/7
- swap dbt-core to using the new package

We can start on this sooner, though, to de-risk the work during the port over.

This issue captures the final switch.

**Comment by emmyoop** [comment]
Doing this now since we're blocked on releasing core until it's done.  Releasing `dbt-common` is being done manually for the moment.
